### ISSUE TITLE
How Set A STARTUP CMD On Python

### ISSUE THREAD

**Issue by ggkk77121** [Luxxy-Hosting/host-bot#8]
[
![image](https://user-images.githubusercontent.com/93269061/168461711-426924b2-58ac-4605-b4ec-2483771aaad9.png)
](url)
[
![image](https://user-images.githubusercontent.com/93269061/168461718-9154e9ac-cfba-4d84-80e1-9aa224fa8c14.png)
](url)

[
![image](https://user-images.githubusercontent.com/93269061/168461724-3e7471b7-6ce0-4e58-b666-f20abcd31992.png)
](url)

**Comment by OxyZachary** [comment]
edit it in startup
